{% set version = "0.4.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-riskclustr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/riskclustr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/riskclustr/riskclustr_{{ version }}.tar.gz
  sha256: 2f3503f0ae75172100efaa8b08aa46c47d393ca193a81dac33e158f39d95b7ac

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-matrix
    - r-aod
    - r-gtools
    - r-mlogit
    - r-stringr
  run:
    - r-base
    - r-matrix
    - r-aod
    - r-gtools
    - r-mlogit
    - r-stringr

test:
  commands:
    - $R -e "library('riskclustr')"           # [not win]
    - "\"%R%\" -e \"library('riskclustr')\""  # [win]

about:
  home: http://www.emilyzabor.com/riskclustr/, https://github.com/zabore/riskclustr
  license: GPL-2.0-only
  summary: 'A collection of functions related to the study of etiologic heterogeneity both across disease subtypes and across individual disease markers. The included functions allow one to quantify the extent of etiologic heterogeneity in the context of a case-control study, and provide p-values to test for etiologic heterogeneity
    across individual risk factors. Begg CB, Zabor EC, Bernstein JL, Bernstein L, Press MF, Seshan VE (2013) <doi: 10.1002/sim.5902>.'
  license_family: GPL2
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - blankenberg

# Package: riskclustr
# Type: Package
# Title: Functions to Study Etiologic Heterogeneity
# Version: 0.2
# Authors@R: person(given = "Emily C.", family = "Zabor", email = "zabore2@ccf.org", role = c("aut", "cre"))
# Description: A collection of functions related to the study of etiologic heterogeneity both across disease subtypes and across individual disease markers. The included functions allow one to quantify the extent of etiologic heterogeneity in the context of a case-control study, and provide p-values to test for etiologic heterogeneity across individual risk factors. Begg CB, Zabor EC, Bernstein JL, Bernstein L, Press MF, Seshan VE (2013) <doi: 10.1002/sim.5902>.
# Depends: R (>= 3.5)
# License: GPL-2
# URL: http://www.emilyzabor.com/riskclustr/, https://github.com/zabore/riskclustr
# BugReports: https://github.com/zabore/riskclustr/issues
# Encoding: UTF-8
# Imports: aod, mlogit, gtools, stringr, Matrix
# Language: en-US
# LazyData: true
# RoxygenNote: 6.1.1
# VignetteBuilder: knitr
# Suggests: testthat, covr, rmarkdown, dplyr, knitr, usethis
# NeedsCompilation: no
# Packaged: 2019-09-06 14:19:36 UTC; ZABORE2
# Author: Emily C. Zabor [aut, cre]
# Maintainer: Emily C. Zabor <zabore2@ccf.org>
# Repository: CRAN
# Date/Publication: 2019-09-07 15:10:02 UTC
