appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
travis:
  secure:
    BINSTAR_TOKEN: QzopVFpR/H3OhCkm01YwgbglnMX0n2hBWkdoPLe6+FUjTHxq5pwQEpvN7548WKmcRNNG/Zd/7MvUDAlRnmIiK8KEdTMsmRxvwWlbHgjUloCXtDdnr/y1PZe1WJ/eTDTKEZ2xId6G5c8xL6So9BxH3DwumfdfbyzBXGItuw1lFPlWrbi7cezX01btv2HRhm7lng2R0ZHNCbeTYL+CJbMPAqbgggTAbaDAt9ZQMpGMVhpS+esAdcfh/zWxyDo5H1xZmciP0DM+j4SU4lTyAQvHqs3Xr2P+RjCKiK+xdR2ukYgMYv5ixAO1VUhsQB5E3du8OnbwI+rBXQzIYXiqep7QhoHTNyErfZ71pe6KpJhE9wMqv5xg0Qv8cM4MxxH4905xSxLmCHThyJ+sSvrQ/RSZZh49AN/UBYJXqxQ6nYvseBNRk6PedSxOma08WaqP2ZWaAoH9OYamZ0FUFXdtblGfNfLemZaepR3Dnhbptx704SnLcOXuaIsEaV9nxYDsGVILrlt6fGXSKJb3mLizANmCU2dB9IeasIutN4zUPrFfb7A6bTT4+Ltcmb1bv0oktkUv7cum1wuwDD2vTBAg8L7p+R70DJtKpuwOSu9uPvc2CwNFTPVx2fLJy+DsXuIyMiGCCc1O9pcUh8REu1Q7PjiLAvKZPt++A2WBTXj33a6Okq0=
conda_forge_output_validation: true
